### ISSUE TITLE
App is crashing when adding location reminder on android 4.1.2

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#17]
I was trying to add a location reminder using android emulator (target Google API, platform 4.1.2) but every time I click 'Done' the app crashes. The error I'm getting is 'unfortunately ohmage-dev has stopped'.

**Comment by ctrance** [comment]
03-25 10:59:44.846: E/Trace(4504): error opening trace file: No such file or directory (2)
03-25 10:59:46.865: E/AndroidRuntime(4504): FATAL EXCEPTION: main
03-25 10:59:46.865: E/AndroidRuntime(4504): java.lang.RuntimeException: Unable to start service org.ohmage.triggers.types.location.LocTrigService@41271298 with Intent { act=org.ohmage.triggers.types.location.LocTrigService.start_trigger cmp=org.ohmage.dev/org.ohmage.triggers.types.location.LocTrigService (has extras) }: java.lang.IllegalArgumentException: requested provider network doesn't exisit
03-25 10:59:46.865: E/AndroidRuntime(4504):     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2507)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at android.app.ActivityThread.access$1900(ActivityThread.java:130)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at android.os.Handler.dispatchMessage(Handler.java:99)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at android.os.Looper.loop(Looper.java:137)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at android.app.ActivityThread.main(ActivityThread.java:4745)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at java.lang.reflect.Method.invokeNative(Native Method)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at java.lang.reflect.Method.invoke(Method.java:511)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at dalvik.system.NativeStart.main(Native Method)
03-25 10:59:46.865: E/AndroidRuntime(4504): Caused by: java.lang.IllegalArgumentException: requested provider network doesn't exisit
03-25 10:59:46.865: E/AndroidRuntime(4504):     at android.os.Parcel.readException(Parcel.java:1429)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at android.os.Parcel.readException(Parcel.java:1379)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:659)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at android.location.LocationManager._requestLocationUpdates(LocationManager.java:664)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at android.location.LocationManager.requestLocationUpdates(LocationManager.java:486)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at org.ohmage.triggers.types.location.LocTrigService.startGPS(LocTrigService.java:809)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at org.ohmage.triggers.types.location.LocTrigService.startSampling(LocTrigService.java:557)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at org.ohmage.triggers.types.location.LocTrigService.updateSamplingStatus(LocTrigService.java:592)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at org.ohmage.triggers.types.location.LocTrigService.onStartCommand(LocTrigService.java:298)
03-25 10:59:46.865: E/AndroidRuntime(4504):     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2490)
03-25 10:59:46.865: E/AndroidRuntime(4504):     ... 10 more
03-25 11:00:38.486: E/ThrottleService(1483): problem during onPollAlarm: java.lang.IllegalStateException: problem parsing stats: java.io.FileNotFoundException: /proc/net/xt_qtaguid/iface_stat_all: open failed: ENOENT (No such file or directory)
03-25 11:01:15.036: E/StrictMode(1902): A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
03-25 11:01:15.036: E/StrictMode(1902): java.lang.Throwable: Explicit termination method 'close' not called
03-25 11:01:15.036: E/StrictMode(1902):     at dalvik.system.CloseGuard.open(CloseGuard.java:184)
03-25 11:01:15.036: E/StrictMode(1902):     at java.io.RandomAccessFile.<init>(RandomAccessFile.java:128)
03-25 11:01:15.036: E/StrictMode(1902):     at r.u.<init>(SourceFile:15)
03-25 11:01:15.036: E/StrictMode(1902):     at r.v.a(SourceFile:70)
03-25 11:01:15.036: E/StrictMode(1902):     at r.w.a(SourceFile:573)
03-25 11:01:15.036: E/StrictMode(1902):     at r.aq.b(SourceFile:414)
03-25 11:01:15.036: E/StrictMode(1902):     at r.aq.a(SourceFile:400)
03-25 11:01:15.036: E/StrictMode(1902):     at r.f.n_(SourceFile:688)
03-25 11:01:15.036: E/StrictMode(1902):     at t.c.b(SourceFile:72)
03-25 11:01:15.036: E/StrictMode(1902):     at t.c.run(SourceFile:61)
03-25 11:01:15.546: E/StrictMode(1902): A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
03-25 11:01:15.546: E/StrictMode(1902): java.lang.Throwable: Explicit termination method 'close' not called
03-25 11:01:15.546: E/StrictMode(1902):     at dalvik.system.CloseGuard.open(CloseGuard.java:184)
03-25 11:01:15.546: E/StrictMode(1902):     at java.io.RandomAccessFile.<init>(RandomAccessFile.java:128)
03-25 11:01:15.546: E/StrictMode(1902):     at r.u.<init>(SourceFile:15)
03-25 11:01:15.546: E/StrictMode(1902):     at r.v.a(SourceFile:70)
03-25 11:01:15.546: E/StrictMode(1902):     at r.w.a(SourceFile:573)
03-25 11:01:15.546: E/StrictMode(1902):     at r.aq.b(SourceFile:414)
03-25 11:01:15.546: E/StrictMode(1902):     at r.aq.a(SourceFile:400)
03-25 11:01:15.546: E/StrictMode(1902):     at r.f.n_(SourceFile:688)
03-25 11:01:15.546: E/StrictMode(1902):     at r.aP.n_(SourceFile:117)
03-25 11:01:15.546: E/StrictMode(1902):     at t.c.b(SourceFile:72)
03-25 11:01:15.546: E/StrictMode(1902):     at t.c.run(SourceFile:61)
03-25 11:01:16.266: E/StrictMode(1902): A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
03-25 11:01:16.266: E/StrictMode(1902): java.lang.Throwable: Explicit termination method 'close' not called
03-25 11:01:16.266: E/StrictMode(1902):     at dalvik.system.CloseGuard.open(CloseGuard.java:184)
03-25 11:01:16.266: E/StrictMode(1902):     at java.io.RandomAccessFile.<init>(RandomAccessFile.java:128)
03-25 11:01:16.266: E/StrictMode(1902):     at r.u.<init>(SourceFile:15)
03-25 11:01:16.266: E/StrictMode(1902):     at r.v.a(SourceFile:70)
03-25 11:01:16.266: E/StrictMode(1902):     at r.w.a(SourceFile:573)
03-25 11:01:16.266: E/StrictMode(1902):     at r.aq.b(SourceFile:414)
03-25 11:01:16.266: E/StrictMode(1902):     at r.aq.a(SourceFile:400)
03-25 11:01:16.266: E/StrictMode(1902):     at r.f.n_(SourceFile:688)
03-25 11:01:16.266: E/StrictMode(1902):     at t.c.b(SourceFile:72)
03-25 11:01:16.266: E/StrictMode(1902):     at t.c.run(SourceFile:61)
03-25 11:01:16.596: E/StrictMode(1902): A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
03-25 11:01:16.596: E/StrictMode(1902): java.lang.Throwable: Explicit termination method 'close' not called
03-25 11:01:16.596: E/StrictMode(1902):     at dalvik.system.CloseGuard.open(CloseGuard.java:184)
03-25 11:01:16.596: E/StrictMode(1902):     at java.io.RandomAccessFile.<init>(RandomAccessFile.java:128)
03-25 11:01:16.596: E/StrictMode(1902):     at r.u.<init>(SourceFile:15)
03-25 11:01:16.596: E/StrictMode(1902):     at r.v.a(SourceFile:70)
03-25 11:01:16.596: E/StrictMode(1902):     at r.w.a(SourceFile:573)
03-25 11:01:16.596: E/StrictMode(1902):     at r.aq.b(SourceFile:414)
03-25 11:01:16.596: E/StrictMode(1902):     at r.aq.a(SourceFile:400)
03-25 11:01:16.596: E/StrictMode(1902):     at r.f.n_(SourceFile:688)
03-25 11:01:16.596: E/StrictMode(1902):     at r.aP.n_(SourceFile:117)
03-25 11:01:16.596: E/StrictMode(1902):     at t.c.b(SourceFile:72)
03-25 11:01:16.596: E/StrictMode(1902):     at t.c.run(SourceFile:61)
03-25 11:01:22.556: E/Trace(4739): error opening trace file: No such file or directory (2)
03-25 11:01:26.026: E/MapActivity(4739): Couldn't get connection factory client
