### ISSUE TITLE
App stops when changing the device's timezone

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#39]
I was trying to test the timezone impact on responses but came across a different issue. Every time I change the timezone of the device, I'm getting this issue >>The application ohmage-dev (process org.ohmage.dev) has stopped unexpectedly. Please try again.<<

Here's the log:

04-05 16:52:31.219: E/AndroidRuntime(26490): FATAL EXCEPTION: main
04-05 16:52:31.219: E/AndroidRuntime(26490): java.lang.RuntimeException: Unable to instantiate receiver org.ohmage.library.TimeZoneChangedReceiver: java.lang.ClassNotFoundException: org.ohmage.library.TimeZoneChangedReceiver in loader dalvik.system.PathClassLoader[/system/framework/com.google.android.maps.jar:/data/app/org.ohmage.dev-1.apk]
04-05 16:52:31.219: E/AndroidRuntime(26490):    at android.app.ActivityThread.handleReceiver(ActivityThread.java:1773)
04-05 16:52:31.219: E/AndroidRuntime(26490):    at android.app.ActivityThread.access$2400(ActivityThread.java:117)
04-05 16:52:31.219: E/AndroidRuntime(26490):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:981)
04-05 16:52:31.219: E/AndroidRuntime(26490):    at android.os.Handler.dispatchMessage(Handler.java:99)
04-05 16:52:31.219: E/AndroidRuntime(26490):    at android.os.Looper.loop(Looper.java:130)
04-05 16:52:31.219: E/AndroidRuntime(26490):    at android.app.ActivityThread.main(ActivityThread.java:3683)
04-05 16:52:31.219: E/AndroidRuntime(26490):    at java.lang.reflect.Method.invokeNative(Native Method)
04-05 16:52:31.219: E/AndroidRuntime(26490):    at java.lang.reflect.Method.invoke(Method.java:507)
04-05 16:52:31.219: E/AndroidRuntime(26490):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
04-05 16:52:31.219: E/AndroidRuntime(26490):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
04-05 16:52:31.219: E/AndroidRuntime(26490):    at dalvik.system.NativeStart.main(Native Method)
04-05 16:52:31.219: E/AndroidRuntime(26490): Caused by: java.lang.ClassNotFoundException: org.ohmage.library.TimeZoneChangedReceiver in loader dalvik.system.PathClassLoader[/system/framework/com.google.android.maps.jar:/data/app/org.ohmage.dev-1.apk]
04-05 16:52:31.219: E/AndroidRuntime(26490):    at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:240)
04-05 16:52:31.219: E/AndroidRuntime(26490):    at java.lang.ClassLoader.loadClass(ClassLoader.java:551)
04-05 16:52:31.219: E/AndroidRuntime(26490):    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-05 16:52:31.219: E/AndroidRuntime(26490):    at android.app.ActivityThread.handleReceiver(ActivityThread.java:1764)
04-05 16:52:31.219: E/AndroidRuntime(26490):    ... 10 more

**Comment by ctrance** [comment]
This issue has been retested and is fixed now.
